server:
  port: 10800
spring:
  profiles:
    active: ${environment}
#    active: dev
  messages:
    basename: i18n/messages
    encoding: UTF-8
logging:
  level:
    io.doeasy.xcar.mapper: debug
  config: classpath:log4j2.xml